# -*- coding: utf-8 -*-
"""
Created on May 17, 2017
LeetCode problem 389
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more
letter at a random position.

Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"

Output:
e
Explanation: 'e' is the letter that was added.
@author: K Li
"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        N, M = len(s), len(t)
        """if (N==0) or (M==0):
            return """

        result = 0
        for ch in s:
            result ^= ord(ch)

        for ch in t:
            result ^= ord(ch)

        return chr(result)

    def findTheDifference1(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        N, M = len(s), len(t)
        """if (N==0) or (M==0):
            return """

        result = 0
        for n in range(N):
            result ^= (ord(s[n]) ^ ord(t[n]))

        result ^= ord(t[-1])
        return chr(result)
    
if __name__ == '__main__':
    a = Solution()
    testVector = [(" ", "  "),("a", "a1"),("a", "ba"),
                  ("aa", "ab"),("aa", "aab"),
                  ("abcd","abcde")]
    a = Solution()
    for test in testVector:
        print(test[0], test[1])
        print("The difference is ", a.findTheDifference(test[0], test[1]))
        print("The difference is ", a.findTheDifference1(test[0], test[1]))

