# -*- coding: utf-8 -*-
"""
Created on Sun May 18, 2017
LeetCode problem 438
Anagram is generated by reorder character in on word to get a new word.
Given a string s and a non-empty string p, find all the start indices of p's
anagrams in s.

Strings consists of lowercase English letters only and the length of both
strings s and p will not be larger than 20,100.
The order of output does not matter.

Example 1:
Input:
s: "cbaebabacd" p: "abc"
Output:
[0, 6]

Explanation:
The substring with start index = 0 is "cba", which is an anagram of "abc".
The substring with start index = 6 is "bac", which is an anagram of "abc".
Example 2:

Input:
s: "abab" p: "ab"
Output:
[0, 1, 2]
Explanation:
The substring with start index = 0 is "ab", which is an anagram of "ab".
The substring with start index = 1 is "ba", which is an anagram of "ab".
The substring with start index = 2 is "ab", which is an anagram of "ab".

@author: K Li
"""

class Solution(object):
    def findAnagrams(self, s, p):
        """
        :type s: str
        :type p: str
        :rtype: List[int]
        """
        N, M = len(s), len(p)
        result = []
        if N<M:
            return result
        # create a key/counter dictionary for p
        pCounter = {}
        for ch in p:
            pCounter[ch] = pCounter.get(ch,0) + 1
        start, end = 0, 0
        cnt = pCounter.copy()
        #while end<N:
        nMatch = 0
        while (end<N) & (end<(start+M)):
            ch = s[end]
            if ch in cnt:
                if cnt[ch]>0:
                    # still match
                    cnt[ch] = cnt[ch]-1
                    nMatch += 1
                    if nMatch == M:
                        # find a match, remove s[start], matchCounter+1
                        #
                        result.append(start)
                        cnt[s[start]] = cnt[s[start]]+1
                        start += 1
                        nMatch -= 1
                    end += 1
                else:
                    # over matching character
                    # remove all char upto the 1st occurance of value s[end]
                    # update cnt/start/end accordingly
                    while s[start]!= ch:
                        # skip all != ch
                        cnt[s[start]] = cnt[s[start]] + 1
                        start += 1
                        nMatch -= 1
                    # skip 1st occurance of s[end]
                    # while keep cnt[s[end]] and nMatch unchanged
                    #cnt[s[start]] = cnt[s[start]] + 1
                    #nMatch -= 1
                    start += 1
                    end += 1
                    #print(start,end)
            else:
                # non matching character
                # reset
                cnt = pCounter.copy()
                start = end+1
                end = start
                nMatch = 0

        return result

    def findAnagrams1(self, s, p):
        """
        :type s: str
        :type p: str
        :rtype: List[int]
        """
        N, M = len(s), len(p)
        result = []
        if N<M:
            return result
        # create a key/counter dictionary for p
        pCounter = {}
        for ch in p:
            pCounter[ch] = pCounter.get(ch,0) + 1
        start, end = 0, 0
        cnt = pCounter.copy()
        #while end<N:
        nMatch = 0
        while (end<N) & (end<(start+M)):
            ch = s[end]
            if ch in cnt:
                if cnt[ch]>0:
                    # still match
                    cnt[ch] = cnt[ch]-1
                    nMatch += 1
                    if nMatch == M:
                        # find a match, remove s[start], matchCounter+1
                        #
                        result.append(start)
                        cnt[s[start]] = cnt[s[start]]+1
                        start += 1
                        nMatch -= 1
                    end += 1
                else:
                    # over matching character
                    # reset, this could be optimized
                    cnt = pCounter.copy()
                    start += 1
                    end = start
                    nMatch = 0
                    #print(start,end)
            else:
                # non matching character
                # reset
                cnt = pCounter.copy()
                start = end+1
                end = start
                nMatch = 0

        return result

if __name__ == '__main__':
    a = Solution()
    testVector = [("", ""), ("abab", "ab"),
                  ("abceabc", "abc"),
                  ("abcabcabc", "abc"),
                  ("babacd", "abc"),
                  ("cbaebabacd", "abc"),
                  ("ana gram", "nagaram")]
    a = Solution()
    for test in testVector:
        print(test[0], test[1])
        indices = a.findAnagrams(test[0],test[1])
        print(a.findAnagrams(test[0],test[1]))
        print(a.findAnagrams1(test[0],test[1]))

