# -*- coding: utf-8 -*-
"""
Created on Sun May 14, 2017
LeetCode problem 242
Given two strings s and t, determine if t is an anagram of s.
Anagram is generated by reorder character in on word to get a new word.

For example,
s = "anagram", t = "nagaram", return true.
s = "rat", t = "car", return false.

Note:
You may assume the string contains only lowercase alphabets.

Follow up:
What if the inputs contain unicode characters? How would you adapt your
solution to such case?

@author: K Li
"""

class Solution(object):
    def isAnagram(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: bool
        Anagram is generated by reorder character in on word to get a new word.
        Properties:
        1. Sorted character of anagram words are identical
        2. Frequency count of character of anagram words are identical
        3. Python3 can handle unicode, so no need for extra code to handle unicode.
        """
        if (len(s)!=len(t)):
            return False
        charCounter = {}
        for s1 in s:
            charCounter[s1] = charCounter.get(s1,0)+1
        for t1 in t:
            cnt = charCounter.get(t1,0)-1
            if cnt<0:
                return False
            charCounter[t1] = cnt
        return True

    def isAnagram1(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: bool
        Anagram is generated by reorder character in on word to get a new word.
        Properties:
        1. Sorted character of anagram words are identical
        2. Frequency count of character of anagram words are identical
        3. Python3 can handle unicode, so no need for extra code to handle unicode.
        """
        if (len(s)!=len(t)):
            return False
        so = sorted(s)
        to = sorted(t)
        return so==to

if __name__ == '__main__':
    a = Solution()
    testVector = [("", ""), ("a a b c d","   abcda "),
                  ("anagram", "nagaram"),
                  ("rat", "car"),
                  ("paper", "title"),
                  ("aacc","ccac"),
                  ("abab", "aabb"),
                  ("earth", "heart"),
                  ("李克民","克民李")]
    a = Solution()
    for test in testVector:
        print(test[0], test[1])
        flag = a.isAnagram(test[0],test[1])
        print("\tIs %s is anagram."%('' if flag else 'NOT'))

